# Generated by Django 3.0.7 on 2020-06-03 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20200603_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placeimage',
            old_name='ulr',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.Place', verbose_name='Место'),
        ),
    ]
