# Generated by Django 3.0.7 on 2020-06-03 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20200603_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placeimage',
            old_name='url',
            new_name='image',
        ),
    ]
