# Generated by Django 3.0.7 on 2020-06-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_place_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='position',
        ),
        migrations.AddField(
            model_name='placeimage',
            name='position',
            field=models.IntegerField(blank=True, null=True, verbose_name='Позиция'),
        ),
    ]
