# Generated by Django 3.0.7 on 2020-08-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_auto_20200816_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.DecimalField(db_index=True, decimal_places=7, max_digits=10, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lng',
            field=models.DecimalField(db_index=True, decimal_places=7, max_digits=10, verbose_name='Долгота'),
        ),
    ]
