# Generated by Django 3.0.7 on 2020-08-16 17:51

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_auto_20200816_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='long_description',
            field=tinymce.models.HTMLField(blank=True, db_index=True, verbose_name='Длинное описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='image',
            field=models.ImageField(db_index=True, upload_to='images', verbose_name='Фотография места'),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='position',
            field=models.IntegerField(db_index=True, verbose_name='Позиция'),
        ),
    ]
